const deck = [
  "twoDiamonds",
  "twoHearts",
  "twoSpades",
  "twoClubs",
  "threeDiamonds",
  "threeHearts",
  "threeSpades",
  "threeClubs",
  "fourDiamonds",
  "fourHearts",
  "fourSpades",
  "fourClubs",
  "fiveDiamonds",
  "fiveHearts",
  "fiveSpades",
  "fiveClubs",
  "sixDiamonds",
  "sixHearts",
  "sixSpades",
  "sixClubs",
  "sevenDiamonds",
  "sevenHearts",
  "sevenSpades",
  "sevenClubs",
  "eightDiamonds",
  "eightHearts",
  "eightSpades",
  "eightClubs",
  "nineDiamonds",
  "nineHearts",
  "nineSpades",
  "nineClubs",
  "tenDiamonds",
  "tenHearts",
  "tenSpades",
  "tenClubs",
  "jackDiamonds",
  "jackHearts",
  "jackSpades",
  "jackClubs",
  "queenDiamonds",
  "queenHearts",
  "queenSpades",
  "queenClubs",
  "kingDiamonds",
  "kingHearts",
  "kingSpades",
  "kingClubs",
  "aceDiamonds",
  "aceHearts",
  "aceSpades",
  "aceClubs",
];

const shuffleDeck = () => {
  const shuffled = [...deck].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, 5); // Lấy 5 lá đầu tiên sau khi xáo trộn
};

export default shuffleDeck